# This provisions a VM that can manage the kubernetes swarm in Digital Ocean
# To start using on Windows:
# - Install chocolatey https://chocolatey.org/
# - Start an elevated prompt (Bash run as administrator is fine)
# - `choco install vagrant`
# - `choco install virtualbox`
# - close elevated prompt
# - open regular prompt in this window
# - `vagrant up`
# - `vagrant ssh`
# - Some secrets will need to be populated in the ./~/.config directory

# TODO: https://github.com/hashicorp/vagrant/issues/4791
# TODO: https://github.com/hashicorp/vagrant/issues/9071

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/precise64'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '1024'
  end

  # Install terraform
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline =
      "sudo apt-get install unzip" +
      " && wget -q https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" +
      " && unzip terraform_0.11.7_linux_amd64.zip" +
      " && sudo mv terraform /usr/local/bin/" +
      " && terraform -v"
  end

  # Install terraform-provider-ct
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline =
      "wget -q https://github.com/coreos/terraform-provider-ct/releases/download/v0.2.1/terraform-provider-ct-v0.2.1-linux-amd64.tar.gz" +
      " && tar xzf terraform-provider-ct-v0.2.1-linux-amd64.tar.gz" +
      " && sudo mv terraform-provider-ct-v0.2.1-linux-amd64/terraform-provider-ct /usr/local/bin/" +
      " && echo providers { ct = \"/usr/local/bin/terraform-provider-ct\" } >> ~/.terraformrc"
  end

  # make folders for screts
  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline =
       "mkdir -p ~/.config/digital-ocean"
     + "echo DIGITAL_OCEAN_TOKEN_HERE > ~/.config/digital-ocean/token"
     + "echo please populate all .config files with secrets"
  end

  # config.vm.synced_folder "/~/", "/home/vagrant/", create: true
end
