apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollem-dev-deployment
spec:
  selector:
    matchLabels:
      app: rollem-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: rollem-dev
    spec:
      containers:
      - name: rollem
        image: lemtzas/rollem-discord:1.12.12
        #imagePullPolicy: Never
        env:
        - name: 'DISCORD_BOT_USER_TOKEN'
          valueFrom:
            secretKeyRef:
              name: rollem-dev
              key: DISCORD_BOT_USER_TOKEN
        - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          valueFrom:
            secretKeyRef:
              name: rollem-dev
              key: APPINSIGHTS_INSTRUMENTATIONKEY
        # - name: 'MONGODB_ROOT_PASSWORD'
        #   valueFrom:
        #     secretKeyRef:
        #       name: dicebag-mongodb
        #       key: mongodb-root-password
        # - name: 'MONGODB_ADDRESS'
        #   value: 'mongodb://dicebag-mongodb.rollem.svc.cluster.local:27017'