{
 "title": "Rollem Prod",
 "tags": [ "rollem" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Popularity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(servers{job=\"default/rollem-next\"})",
     "legendFormat": "rollem-next"
    },
    {
     "expr": "sum(servers{job=\"default/rollem-prod\"})",
     "legendFormat": "rollem-prod"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(users{job=\"default/rollem-next\"})",
     "legendFormat": "rollem-next"
    },
    {
     "expr": "sum(users{job=\"default/rollem-prod\"})",
     "legendFormat": "rollem-prod"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Servers (Next)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max by(shard) (servers{job=\"default/rollem-next\"})",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Servers (Prod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "max by(shard) (servers{job=\"default/rollem-prod\"})",
       "legendFormat": "__auto"
      },
      { "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Rolls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Rolls (Prod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(handler_subtype) (increase(rollem_handlers_used{job=\"default/rollem-prod\", handler_type=\"roll\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rolls (Next)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by(handler_subtype) (increase(rollem_handlers_used{job=\"default/rollem-next\", handler_type=\"roll\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Handled Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Handled Events (Prod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"default/rollem-prod\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Handled Events (Next)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(shard) (increase(rollem_events_processed{job=\"default/rollem-next\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Prod Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "min by(shard) ((time() - process_start_time_seconds{job=\"default/rollem-prod\"}) / 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "min by(shard) ((time() - process_start_time_seconds{job=\"default/rollem-next\"}) / 60)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}