#!/bin/bash

# set current working directory to the root folder
cd "${0%/*}/../../.." || exit
source_file_name=source.env

# generates source.env files for all sets of secrets
for folder_path in infra/k8s/secrets/*/; do
    target_source_file=$folder_path$source_file_name

    echo generating $target_source_file
    echo '# This file is generated by' $0 > $target_source_file
    echo "# This file can be used to load secrets via \`source source.env\`." >> $target_source_file

    # turn all the filename-content pairs into exported env values
    for file in $folder_path*; do
        key=$(basename $file)
        secret=$(<$file)
        
        if [[ $key == "source.env" ]]; then
            continue
        fi

        echo export $key=$secret >> $target_source_file
    done
done